### ISSUE TITLE
Incorrect bounds for prettyprinter-ansi-terminal

### ISSUE THREAD

**Issue by phlummox** [Mesabloo/diagnose#19]
The bounds for `prettyprinter-ansi-terminal` are given as ">=1.1.0 && <2":

https://github.com/Mesabloo/diagnose/blob/b40f573a0a75586e2b19c1326ccade54c2b4a336/diagnose.cabal#L74

However, these bounds are incorrect: `diagnose` requires `prettyprinter-ansi-terminal` >= 1.1.2, and compilation will fail if versions of `prettyprinter-ansi-terminal` lower than that are used.

Specifically, in module `Error.Diagnose.Diagnostic.Internal`, Prettyprinter.Render.Terminal is imported:

https://github.com/Mesabloo/diagnose/blob/b40f573a0a75586e2b19c1326ccade54c2b4a336/src/Error/Diagnose/Diagnostic/Internal.hs#L35

This module does not exist in versions of `prettyprinter-ansi-terminal` < 1.2 (see e.g. [prettyprinter-ansi-terminal-1.1.1.2](https://hackage.haskell.org/package/prettyprinter-ansi-terminal-1.1.1.2)).

**Comment by Mesabloo** [comment]
Thanks for the report. That is indeed an oversight. I guess stack always chose at least version 1.1.2 for me so I never had the issue.
In the meantime, you can fix the version of `prettyprinter-ansi-terminal` used in your `stack.yaml` (if you are using stack; unfortunately I don't know how to do that with cabal alone).

**Comment by phlummox** [comment]
No worries - fixing it is no problem, but I thought I'd best report the issue so the bounds can be fixed for future versions. Cheers :)
