### ISSUE TITLE
Incorrect bounds for unordered-containers

### ISSUE THREAD

**Issue by phlummox** [Mesabloo/diagnose#20]
The bounds for `unordered-containers` are given as "==0.2.*":

https://github.com/Mesabloo/diagnose/blob/5df8d9097b66867fcde2a704084dcd32887e90f7/diagnose.cabal#L76

But this is incorrect: `diagnose` will not build with versions of `unordered-containers` < 0.2.11. It uses the `!?` function from Data.HashMap.Lazy, here:

https://github.com/Mesabloo/diagnose/blob/5df8d9097b66867fcde2a704084dcd32887e90f7/src/Error/Diagnose/Report/Internal.hs#L519

and that function was not introduced into `unordered-containers` until version 0.2.11 (see [here][unord]).

[unord]: https://hackage.haskell.org/package/unordered-containers-0.2.19.1/docs/Data-HashMap-Lazy.html#v:-33--63-

**Comment by Mesabloo** [comment]
This is also an oversight. This will be fixed together with #19.

**Comment by Mesabloo** [comment]
Weird, I guess it did not detect this issue was fixed too from the message of the commit.
