### ISSUE TITLE
Relax bounds to allow text-2.0

### ISSUE THREAD

**Issue by mordae** [Mesabloo/diagnose#4]
It works fine with `cabal build --allow-newer=text`, so I assume you can relax the bounds on Hackage.

**Comment by mordae** [comment]
Also, thanks for a marvelous package.

**Comment by Mesabloo** [comment]
Thank you!

I have just checked, and the dependency on `text` is in fact needed just for the tests.
There are a few things I want to get done before releasing a new minor version (see e.g. #3).
In the meantime, I'll just push a fix for this on master! :slightly_smiling_face:

**Comment by Mesabloo** [comment]
This fix has been published in version `1.8.2`. The library does not depend anymore on `text`.
Thanks for the report!
