### ISSUE TITLE
Consider exporting `prettyDiagnostic`

### ISSUE THREAD

**Issue by kquick** [Mesabloo/diagnose#5]
The current functionality requires an output to a file handle, but allowing the conversion to a `Prettyprinter.Doc` format would enable this to be embedded in other Doc output and managed as needed by client applications.  Would exporting `prettyDiagnostic` be a reasonable update?

**Comment by Mesabloo** [comment]
Ideally, there would be no such function.
However, as the `Pretty` instance cannot convey colors, this cannot be done that way.
Also, since we require some parameters (e.g. for unicode characters), this is not possible.

There are 3 options:
1. Create a `Pretty` instance, which gets rid of the colors and adds default parameters (basically `pretty = unAnnotate . prettyDiagnostic True True`).
  This is not a great solution in my opinion;
2. Expose the function `prettyDiagnostic` and let the user remove colors if needed (using `unAnnotate`).
  This just needs a small pass on documentation, which is not actually up to date;
3. Expose the function and add a parameter to remove colors conditionnaly (similarly to `printDiagnostic`).
  This needs a little bit of refactoring but should be fine.

Among all those options, I prefer the 2nd one, as it is the simpler one.

**Comment by Mesabloo** [comment]
This was included in the version [`1.9.0`](https://hackage.haskell.org/package/diagnose-1.9.0)!

**Comment by kquick** [comment]
I'd also like to suggest that instead of annotating the `PP.Doc` directly with `AnsiStyle`, you could defined your own annotation type that identified the significant portions of the doc (e.g. `data DiagnoseAnn = ErrorAnn | WarningAnn | ThisAnn | WhereAnn | HintAnn | ...`).  Then in the `printDiagnostic` it could `reAnnotate` to convert the `DiagnoseAnn` into the `AnsiStyle` annotations you provide, but this would allow the `prettyDiagnostic` results to be easily `reAnnotate`d into whatever styling is desired by the client code.  The `DiagnoseAnn` is more easily matched than `AnsiStyle`, and is also more informative (e.g. currently `Color Red` is used for both the header "error" text and for the `This` portion) for reannotation.

**Comment by Mesabloo** [comment]
That is a great idea I actually did not think about.
This allows for more customization (the basic style will still be an option in a specific package) on how stuff is rendered.

This will take a bit of work to introduce into the library, but I think it is completely worth it.
Thanks for the suggestion!

**Comment by Mesabloo** [comment]
I have added in da0ccd5933cbe44fbd381be2afeb8982c2fedc41 a way of handling style simply via a maping `Annotation -> AnsiStyle`, similar to this https://github.com/Mesabloo/diagnose/blob/da0ccd5933cbe44fbd381be2afeb8982c2fedc41/src/Error/Diagnose/Style.hs#L90-L102

That way, people can create their own styles (or themes, whatever you want to call it) and can feed them to `printDiagnostic`.
`prettyDiagnostic`, on the other hand, must have the style applied to it (e.g. `myCustomStyle $ prettyDiagnostic ...`).

This seems to implement your suggestion, which I quite like.
I will be closing this issue for the next release.

**Comment by kquick** [comment]
Excellent!  I'm glad I was able to help improve this library: I'm already enjoying reading errors (sad, but true).

Looking over the changes, I noticed a couple of spots where you might want to update the documentation:
* https://github.com/Mesabloo/diagnose/blob/master/README.md?plain=1#L81-L82
* https://github.com/Mesabloo/diagnose/blob/master/src/Error/Diagnose.hs#L14 (only describes file output)
* https://github.com/Mesabloo/diagnose/blob/master/src/Error/Diagnose.hs#L121 (references the wrong prettyprinter package)

And all the module copyright dates.

**Comment by Mesabloo** [comment]
Thanks for looking into it!
All the above issues should be fixed now. Some of them were details I completely missed when changing the pretty-printing library used internally (I used to use `ansi-wl-pprint` but switch to `prettyprinter` as the former got deprecated).

> I'm already enjoying reading errors (sad, but true).

That is quite funny to read actually! This may be one of the downsides of this library. :joy:

**Comment by Mesabloo** [comment]
Sorry for the delay.
All these new changes have been incorporated in the new version [`2.0.0`](https://hackage.haskell.org/package/diagnose-2.0.0). :tada: (see the module `Error.Diagnose.Style`)
