### ISSUE TITLE
Integration with LSP?

### ISSUE THREAD

**Issue by luc-tielen** [Mesabloo/diagnose#9]
The docs mention integration with LSP via the `diagnosticToJson` function, but no other information is given on how to do this.

I'm new to LSP myself, could you provide some pointers where to start looking for more information?
(Or add a section to `Diagnose` docs somewhere on how to quickly/easily integrate with LSP?)

Thanks!

**Comment by Mesabloo** [comment]
> I'm new to LSP myself, could you provide some pointers where to start looking for more information?

I unfortunately cannot. :(

Initially, I wrote that `diagnosticToJson` function (which uses Aeson under the hood) as a way to export the diagnostic from within the compiler (meaning that your compiler would still need something along the lines of a `--lsp` flag to toggle this on/off).
That way, your LSP server could simply invoke the compiler (with that special flag) and fetch its stderr and parse it as JSON.
This is way better than trying to parse the error itself when encountered, and gives all the necessary information directly (e.g. position in the original source code in codepoints).
I have absolutely no idea how to write a LSP server for any language whatsoever so there's nothing more that I can tell really, other than my original thoughts.

Also, if you are willing to use the JSON functions, you will need to toggle the flag `diagnose:json` in your cabal/stack configuration.
On stack, you'd add 
```yaml
flags:
  diagnose:
    json: True
``` 
to your `stack.yaml` and on cabal you'd add 
```cabal
package diagnose
  flags: +json
``` 
to your `cabal.project`.

---------

> That way, your LSP server could simply invoke the compiler (with that special flag) and fetch its stderr and parse it as JSON.

I believe there are way better ways to do this.
For example, I designed my own compiler to be a set of libraries which may be used as such to only parse, typecheck or other things. That way, a LSP server does not seem to have any problem with compiler integration (this requires the LSP server to be written in the same programming language that the compiler, but this isn't such a problem really).

**Comment by luc-tielen** [comment]
Thanks for the quick and thorough reply!

I think I will skip the `diagnosticsToJson` function then, since my plan was to integrate the LSP directly into the compiler using the Haskell `lsp` library anyway. :)
 
The harder thing will most likely be getting certain information (such as positions) in the place I need it (without re-architecting the whole error handling/rendering part of my compiler).

In case you're interested, I'm using diagnose in [eclair](https://github.com/luc-tielen/eclair-lang.git) for the CLI diagnostics already.

**Comment by Mesabloo** [comment]
There's just one micro problem: currently, it is impossible to inspect the content of a `Diagnostic`, which may be quite a problem for LSP servers (which will want to know where do the errors occur).
This should be quite easily fixed by adding a very simple function `reportsOf (Diagnostic _ reports) = DList.toList reports` somewhere in the `Error.Diagnose.Diagnostic.Internal` and re-exporting it in `Error.Diagnose.Diagnostic` or directly re-exporting the constructor (which I'd rather not, in order to keep the internal structure private).
I don't have the time right now to do it though.

> In case you're interested, I'm using diagnose in [eclair](https://github.com/luc-tielen/eclair-lang.git) for the CLI diagnostics already.

Hey it's been quite a while since I starred your project in fact! :) (I am the 16th star)
Pretty cool project!

**Comment by luc-tielen** [comment]
> There's just one micro problem: currently, it is impossible to inspect the content of a `Diagnostic`, which may be quite a problem for LSP servers (which will want to know where do the errors occur). This should be quite easily fixed by adding a very simple function `reportsOf (Diagnostic _ reports) = DList.toList reports` somewhere in the `Error.Diagnose.Diagnostic.Internal` and re-exporting it in `Error.Diagnose.Diagnostic` or directly re-exporting the constructor (which I'd rather not, in order to keep the internal structure private).
> 
> **EDIT:** we also need to create a few helper functions for `Report`s as well, as their internal structure is also not exposed. I think we can safely export the constructor, and/or create pattern synonyms for common functions such as `warn` and `err`.
> 
> I don't have the time right now to do it though.

I can take a look at it, since I need it anyway. Least I can do. :smile:

Initially I was also thinking just to expose the constructors, but then you won't notice the breaking changes. With a function you see the breaking changes in the library itself. And yeah, we will need multiple functions (I think atleast `reportsOf` and `markersOf`, since I need to know the location of the `This` marker). 

> Hey it's been quite a while since I starred your project in fact! :) (I am the 16th star) Pretty cool project!

I didn't know that! Thanks :blush:
